---
- name: Apply updates to OpenShift cluster
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Get an existing Service object
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kubeconfig: kubeconfig
        kind: ClusterVersion
        name: version
        validate_certs: no
      register: versions

    #  - name: Apply updates
    #  k8s:
    #    state: present
    #    definition:
    #      apiVersion: config.openshift.io/v1
    #      kind: ClusterVersion
    #      metadata:
    #        name: version
    #      spec:
    #        desiredUpdate:
    #          version: "{{ available_updates.resources[0].spec.versions[-1] }}"
    #      auth:
    #        bearer_token: "{{ auth_result.token }}"
    #  register: upgrade_output

    - name: Display cluster_name
      debug:
        msg: "{{ cluster_name }}"
      ignore_errors: yes 

    - name: Display upgrade_versions
      debug:
        msg: "{{ upgrade_versions }}"
      ignore_errors: yes 


    - name: debug
      debug:
        msg: "{{ versions }}"
