---
- name: Get available updates in OpenShift cluster
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Authenticate to the Kubernetes API
      k8s_auth:
        host: https://api.fiserv.openshift.training:6443
        username: alex
        password: Pass123!
        validate_certs: no
      register: auth_result

    - name: debug result
      debug:
        msg: "{{ auth_result  }}"
      
    - name: Get available updates token
      k8s_info:
        kind: ClusterVersion
        api_version: config.openshift.io/v1
        namespace: openshift-config
        auth:
          bearer_token: "{{ auth_result.openshift_auth.token }}"
      register: available_updates
      when: auth_result.openshift_auth.token is defined

    - name: Get available updates api_key
      k8s_info:
        kind: ClusterVersion
        api_version: config.openshift.io/v1
        namespace: openshift-config
        api_key: "{{ auth_result.openshift_auth.api_key }}"
      register: available_updates
      when: auth_result.openshift_auth.api_key is defined
     

    - name: Display available updates
      debug:
        msg: "{{ available_updates }}"
