---
- name: Get available updates in OpenShift cluster
  hosts: localhost
  connection: local
  gather_facts: false
  module_defaults:
    group/redhat.openshift.openshift:
      host: https://api.openshift.training:6443

  tasks:
    - name: Get pass for admin
      delegate_to: localhost
      ansible.builtin.include_vars:
        file: vars.yaml
        name: config

    - name: debug pass
      delegate_to: localhost
      debug:
        msg: "{{ config.cluster_admin_password }}"

    - name: Log in (obtain access token)
      delegate_to: localhost
      redhat.openshift.openshift_auth:
        username: alex
        password: "{{ config.cluster_admin_password }}"
        validate_certs: no
      register: auth_result

    - name: debug result
      delegate_to: localhost
      debug:
        msg: "{{ auth_result.openshift_auth.api_key }}"
      
    - name: Get available updates api_key
      delegate_to: localhost
      kubernetes.core.k8s_info:
        kind: ClusterVersion
        api_version: config.openshift.io/v1
        namespace: openshift-config
        api_key: "{{ auth_result.openshift_auth.api_key }}"
        validate_certs: false
      register: available_updates
      when: auth_result.openshift_auth.api_key is defined

    - name: Set fact current channel
      ansible.builtin.set_fact:
        channel: "{{ available_updates.resources[0].spec.channel }}"
        updates: "{{ available_updates.resources[0].status }}"

    - name: Display available updates
      delegate_to: localhost
      debug:
        msg: "{{ updates | json_query( \"availableUpdates[?contains(channels,'\" + channel + \"')].version\") }}"

    - name: Apply multiple patch operations to an existing Pod
      kubernetes.core.k8s_json_patch:
        api_version: v1
        kind: ConfigMap
        namespace: openshift-config
        name: admin-acks
        patch:
          - op: replace
            path: /spec/data/ack-4.13-kube-1.27-api-removals-in-4.14
            value: true
          