---
- name: Get available updates in OpenShift cluster
  hosts: localhost
  connection: local
  gather_facts: false
  module_defaults:
    group/redhat.openshift.openshift:
      host: https://api.openshift.training:6443

  tasks:
    - name: Get pass for admin
      ansible.builtin.include_vars:
        file: vars.yaml
        name: admin_pass

    - name: Log in (obtain access token)
      delegate: localhost
      redhat.openshift.openshift_auth:
        username: alex
        password: Pass123!
        validate_certs: no
      register: auth_result

    - name: debug result
      debug:
        msg: "{{ auth_result.openshift_auth.api_key }}"
      
    - name: Get available updates api_key
      delegate: localhost
      kubernetes.core.k8s_info:
        kind: ClusterVersion
        api_version: config.openshift.io/v1
        namespace: openshift-config
        api_key: "{{ auth_result.openshift_auth.api_key }}"
        validate_certs: false
      register: available_updates
      when: auth_result.openshift_auth.api_key is defined
     
    - name: Display available updates
      debug:
        msg: "{{ available_updates.resources[0].status.availableUpdates }}"
